### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by Pang** [cPango/KnightsAndWarlocks#1]
## **Ideas to implement**
- [x] Fix health to sync with Npc attacks in real-time
- [x] Give each class a special move
- [x] Make enemies drop an item upon death
- [x] Create  combat log which display last 5 actions below menu
- [x] Create smaller combat log for npc (last 3 actions)
- [ ] Change each Npc class' to have unique properties
- [ ] Add levelling system

**Comment by Pang** [comment]
Health now syncs with attacks. Did this by moving the combat menu and npcTimer method into functions in the Program class, then placing the combat menu as a method into the timer

**Comment by Pang** [comment]
Special move/attack added for both classes, warlocks special deals more damage however will now start with less items to replenish health

**Comment by Pang** [comment]
Enemies now have a chance to drop items upon death, either a health item or a special attack potion. Items are not capped however chances of loot are not high.

**Comment by Pang** [comment]
Combat log created using Queue type, inserting player-choices into a method that checks how many items are in the queue & de-queues, then finally copies to an array and loops through each string.

**Comment by Pang** [comment]
Added an npc combat log and created lines on the console to separate UI elements
